Get involved
MissionBit/BAMPWebsite pull request #61
Opened 2020-11-18 02:15 UTC by kingtrentiii

![Capture3](https://user-images.githubusercontent.com/50639823/99473919-71beca80-2900-11eb-85da-e490c67e640d.PNG)

After going to the eye doctor last Friday that I have a red-green color deficiency or deuteranopia. But I don't really notice it tho lol.

2020-11-20 02:22 UTC, coramonokandilos commented
Looks great Trent!

A couple of things:

- I think the modules (Art, Volunteer, etc.) should probably be a bit smaller (both height and width)? So we have more white space on the left and right and so we don't have to scroll too much to be able to see all the elements. Right now, the buttons look very small and I think decreasing the space will help with that!
- The "FAQ" title is missing off the FAQs. 
- Make sure you add all the stuff we still need from BAMP in this [sheet](https://docs.google.com/spreadsheets/d/1mqwwYEvk68-PrNebsHkTjBIHoX3_OfuDpcOOrBAuBck/edit#gid=1423163878).

2020-11-20 02:25 UTC, coramonokandilos requested changes

2020-11-20 02:25 UTC, coramonokandilos commented on get_involved.html
> +            <div class="l-section">
I think there is an indenting issue on this line.

2020-12-05 02:49 UTC, johncip approved these changes
looks good. I updated the footer to be the new structure (see https://github.com/MissionBit/BAMPWebsite/pull/63 ). merging

2020-12-05 02:51 UTC, johncip commented
@coramonokandilos I think you'll have to approve as well before one of us can merge -- I'm not sure if there was anything else, but the indentation you caught is fixed now.

2020-12-09 00:45 UTC, coramonokandilos commented
Looks good to me!

2020-12-09 00:45 UTC, coramonokandilos approved these changes

2020-12-09 00:50 UTC, merged